modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/arollyson/FasterLadderClimbing/issues"
license = "CC-BY-NC-SA 3.0"

[[mods]]
modId = "fasterladderclimbing"
displayName = "Faster Ladder Climbing"
version = "0.2.5"
authors = "JaSpr, forkbomb_"
description = '''
Climb Ladders Faster
'''

#forge
[[dependencies.fasterladderclimbing]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "CLIENT"

#minecraft
[[dependencies.fasterladderclimbing]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19]"
ordering = "NONE"
side = "CLIENT"
