modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="github.com/arollyson/FasterLadderClimbing/issues"

[[mods]]
modId="fasterladderclimbing"
displayName="Faster Ladder Climbing"
version="${version}"
authors="JaSpr, forkbomb_"
description='''
Climb Ladders Faster
'''

#forge
[[dependencies.fasterladderclimbing]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

#minecraft
[[dependencies.fasterladderclimbing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"